sudo: required
language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "lts/*"
install:
  - npm install
before_script:
  - nohup node ./server/index.js &
scripts:
  - npm start
  - npm test
